[project]
name = "f5-automation-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "ansible>=11.7.0",
    "jinja2>=3.1.6",
    "requests>=2.32.4",
]
