virtual:
    lb: "10.1.1.4" # load balancer IP or host name
    app: ansible-test01 # app name
    description: "This is a test" # description for virtaul and pool 
    virtualip: "10.1.20.204" # virtuals IP address
    port: "443" # port the virtual will listen on 
    member_port: "80"
    send_string: "GET /index.html HTTP/1.1\\r\\nHost: app_server\\r\\nConnection: Close\\r\\n\\r\\n" # send string for backend server monitoring
    recv_string: "200 OK" # recieve string from backend servers
    members: # pool member IPs 
      - 10.1.20.101
      - 10.1.20.104




